apiVersion: apps/v1
kind: Deployment
metadata:
  name: misconfig-deploy
  labels:
    app: misconfig
spec:
  replicas: 3
  selector:
    matchLabels:
      app: misconfig
  template:
    metadata:
      labels:
        app: misconfig
    spec:
      containers:
      - name: misconfig-container
        image: nginx:1.23.0
        ports:
        - containerPort: 80