name: notes-backend

services:
  notes:
    build:
      context: .
      target: development
    ports:
      - "3001:80"
    environment:
      - PORT=80
      - DB_URL=mongodb://${NOTES_DB_USER}:${NOTES_DB_PASSWORD}@notes-db/${NOTES_DB_NAME}
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
    networks:
      - notes-backend-network
    depends_on:
      - notes-db
  notes-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    env_file:
      - .env
    volumes:
      - type: volume
        source: notes-data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true

    networks:
      - notes-backend-network

volumes:
  notes-data:

networks:
  notes-backend-network: